project:
  type: website

website:
  title: "Zachary P Dickson"
  navbar: 
    background: primary
    left:
      - href: research.qmd   
      - href: teaching.qmd
      - href: resume.qmd
      - href: datasets.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true



